# Generated by Django 3.2.1 on 2021-05-24 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('shares', models.TextField()),
                ('date_bought', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
