# Generated by Django 3.2.1 on 2021-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='boughtPrice',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positions',
            name='change',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positions',
            name='currentPrice',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positions',
            name='marketValue',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
